### PR TITLE
Create MAINTAINERS.md

### PR DESCRIPTION
**Pull request by FredFousPro**
Create Maintainers File to describe roles of each committers.

### CODE REVIEW

**Comment by FredFousPro** [comment]
ok

**Comment by Sander3003** [comment]
@FredFousPro Is this pull-request ready for review?

**Comment by FredFousPro** [comment]
You can review it.
I will have a modification to do but later.
Regards,

**Comment by Flurb** [comment]
Hi, I have a question!

Does this mean Pull Requests of the compas-cim-mapping repository cannot be reviewed by someone else besides me and Sander?

**Comment by FredFousPro** [comment]
Hi,
Each maintainers (TSC members) can reviews all the PR. Even if, at this moment, it doesn't work for me with your PR, I can't review them. Indeed, I have the green button, but clicking on it do nothing; I think it is a problem with the webbrowser of my Professional computer.
This Maintainers file is mostly to define the "main" maintainers for the different subjects specially for PR from non-maintainers people.
Concerning PR from maintainers, as cross review is mandatory, only another maintainers should perform the review and this case is not treated by the file.

**Comment by Flurb** [comment]
That's okay!

**Review by Flurb — APPROVED** [review]

**Pull request merged**
